// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/extract": {
            "post": {
                "description": "Scrapes the given URL and returns structured content.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extract"
                ],
                "summary": "Extract content from a URL",
                "parameters": [
                    {
                        "description": "URL to extract",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.extractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.httpResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal.errorResponse"
                        }
                    }
                }
            }
        },
        "/extract/graph": {
            "post": {
                "description": "Runs entity extraction and ArangoDB graph population for a result that was previously processed by /extract or /extract/stream.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extract"
                ],
                "summary": "Populate knowledge graph from a previously extracted URL",
                "parameters": [
                    {
                        "description": "URL to index",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.graphRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.httpResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal.extractRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "num_ctx": {
                    "type": "integer",
                    "example": 8192
                },
                "styles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "summary",
                        "takeaways"
                    ]
                },
                "url": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                }
            }
        },
        "internal.graphRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                }
            }
        },
        "internal.httpResult": {
            "type": "object",
            "properties": {
                "channel_name": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content_type": {
                    "$ref": "#/definitions/router.ContentType"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "fetched_at": {},
                "language_code": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "model": {
                    "type": "string"
                },
                "num_ctx": {
                    "type": "integer"
                },
                "style": {
                    "type": "string"
                },
                "styles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "video_id": {
                    "type": "string"
                }
            }
        },
        "router.ContentType": {
            "type": "string",
            "enum": [
                "html",
                "json",
                "xml",
                "binary"
            ],
            "x-enum-varnames": [
                "ContentHTML",
                "ContentJSON",
                "ContentXML",
                "ContentBinary"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Greenclaw API",
	Description:      "Detect-first, escalate-later web scraper with LLM processing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
