package store

import "encoding/json"

const (
	ContentYouTubeVideo    ContentType = "youtube_video"
	ContentYouTubePlaylist ContentType = "youtube_playlist"
	ContentYouTubeChannel  ContentType = "youtube_channel"
)

// YouTubeData holds YouTube-specific extracted data, serialized into Result.RawData.
type YouTubeData struct {
	VideoID       string            `json:"video_id,omitempty"`
	Duration      string            `json:"duration,omitempty"`
	ViewCount     int               `json:"view_count,omitempty"`
	UploadDate    string            `json:"upload_date,omitempty"`
	ChannelName   string            `json:"channel_name,omitempty"`
	ChannelID     string            `json:"channel_id,omitempty"`
	Tags          []string          `json:"tags,omitempty"`
	Captions      []CaptionTrack    `json:"captions,omitempty"`
	AudioPath     string            `json:"audio_path,omitempty"`
	SubtitlePaths map[string]string `json:"subtitle_paths,omitempty"`
	PlaylistItems []PlaylistItem    `json:"playlist_items,omitempty"`
	Processing    []ProcessingResult `json:"processing,omitempty"`
}

// ProcessingResult holds the output of a single LLM processing style.
type ProcessingResult struct {
	Style   string          `json:"style"`
	Content json.RawMessage `json:"content"`
}

// CaptionTrack represents a single caption/subtitle track.
type CaptionTrack struct {
	Language      string `json:"language"`
	LanguageCode  string `json:"language_code"`
	AutoGenerated bool   `json:"auto_generated"`
	Text          string `json:"text"`
}

// PlaylistItem represents a single video in a playlist.
type PlaylistItem struct {
	VideoID string `json:"video_id"`
	Title   string `json:"title"`
	Index   int    `json:"index"`
}
