package youtube

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"greenclaw/internal/store"

	ytlib "github.com/kkdai/youtube/v2"
)

// Client wraps the kkdai/youtube library for video metadata extraction.
type Client struct {
	yt *ytlib.Client
}

// NewClient creates a YouTube client using the given HTTP client.
func NewClient(httpClient *http.Client) *Client {
	return &Client{
		yt: &ytlib.Client{
			HTTPClient: httpClient,
		},
	}
}

// GetVideoMetadata fetches video metadata and returns a populated YouTubeData struct.
func (c *Client) GetVideoMetadata(ctx context.Context, videoID string) (*store.YouTubeData, *ytlib.Video, error) {
	video, err := c.yt.GetVideoContext(ctx, videoID)
	if err != nil {
		return nil, nil, fmt.Errorf("getting video metadata: %w", err)
	}

	data := &store.YouTubeData{
		VideoID:     videoID,
		Duration:    video.Duration.String(),
		ViewCount:   video.Views,
		ChannelName: video.Author,
		ChannelID:   video.ChannelID,
	}

	if video.PublishDate.After(time.Time{}) {
		data.UploadDate = video.PublishDate.Format("2006-01-02")
	}

	// Collect caption track metadata
	for _, cap := range video.CaptionTracks {
		data.Captions = append(data.Captions, store.CaptionTrack{
			Language:      cap.Name.SimpleText,
			LanguageCode:  cap.LanguageCode,
			AutoGenerated: cap.Kind == "asr",
		})
	}

	return data, video, nil
}

// GetPlaylistItems fetches all videos in a playlist.
func (c *Client) GetPlaylistItems(ctx context.Context, playlistID string) ([]store.PlaylistItem, error) {
	playlist, err := c.yt.GetPlaylistContext(ctx, playlistID)
	if err != nil {
		return nil, fmt.Errorf("getting playlist: %w", err)
	}

	items := make([]store.PlaylistItem, 0, len(playlist.Videos))
	for i, v := range playlist.Videos {
		items = append(items, store.PlaylistItem{
			VideoID: v.ID,
			Title:   v.Title,
			Index:   i,
		})
	}
	return items, nil
}
