package youtube

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"greenclaw/internal/store"

	ytlib "github.com/kkdai/youtube/v2"
)

func TestParseTimedTextXML(t *testing.T) {
	xmlData := []byte(`<?xml version="1.0" encoding="utf-8"?>
<transcript>
  <text start="0.0" dur="2.5">Hello world</text>
  <text start="2.5" dur="3.0">This is a test</text>
  <text start="5.5" dur="1.5">with &amp; special &lt;chars&gt;</text>
</transcript>`)

	entries, err := parseTimedTextXML(xmlData)
	if err != nil {
		t.Fatalf("parseTimedTextXML() error = %v", err)
	}

	if len(entries) != 3 {
		t.Fatalf("got %d entries, want 3", len(entries))
	}

	// Check first entry
	if entries[0].Start != 0.0 {
		t.Errorf("entry[0].Start = %f, want 0.0", entries[0].Start)
	}
	if entries[0].Dur != 2.5 {
		t.Errorf("entry[0].Dur = %f, want 2.5", entries[0].Dur)
	}
	if entries[0].Text != "Hello world" {
		t.Errorf("entry[0].Text = %q, want %q", entries[0].Text, "Hello world")
	}

	// Check HTML entity unescaping
	if entries[2].Text != "with & special <chars>" {
		t.Errorf("entry[2].Text = %q, want %q", entries[2].Text, "with & special <chars>")
	}
}

func TestEntriesToPlainText(t *testing.T) {
	entries := []TimedEntry{
		{Start: 0, Dur: 1, Text: "Hello"},
		{Start: 1, Dur: 1, Text: "world"},
		{Start: 2, Dur: 1, Text: "test"},
	}

	got := entriesToPlainText(entries)
	want := "Hello world test"
	if got != want {
		t.Errorf("entriesToPlainText() = %q, want %q", got, want)
	}
}

func TestGetTranscript(t *testing.T) {
	captionXML := `<?xml version="1.0" encoding="utf-8"?>
<transcript>
  <text start="0.0" dur="2.0">First line</text>
  <text start="2.0" dur="2.0">Second line</text>
</transcript>`

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/xml")
		w.Write([]byte(captionXML))
	}))
	defer srv.Close()

	client := &Client{
		yt: &ytlib.Client{HTTPClient: srv.Client()},
	}

	video := &ytlib.Video{
		CaptionTracks: []ytlib.CaptionTrack{
			{
				BaseURL:      srv.URL + "/captions",
				LanguageCode: "en",
				Name: struct {
					SimpleText string `json:"simpleText"`
				}{SimpleText: "English"},
			},
		},
	}

	track, entries, err := client.GetTranscript(context.Background(), video, "en")
	if err != nil {
		t.Fatalf("GetTranscript() error = %v", err)
	}

	if len(entries) != 2 {
		t.Errorf("got %d entries, want 2", len(entries))
	}

	if track.LanguageCode != "en" {
		t.Errorf("track.LanguageCode = %q, want %q", track.LanguageCode, "en")
	}

	want := "First line Second line"
	if track.Text != want {
		t.Errorf("track.Text = %q, want %q", track.Text, want)
	}
}

func TestGetTranscriptNotFound(t *testing.T) {
	client := &Client{
		yt: &ytlib.Client{},
	}

	video := &ytlib.Video{
		CaptionTracks: []ytlib.CaptionTrack{},
	}

	_, _, err := client.GetTranscript(context.Background(), video, "en")
	if err == nil {
		t.Fatal("expected error for missing language")
	}
}

func TestGetAllTranscripts(t *testing.T) {
	captionXML := `<?xml version="1.0" encoding="utf-8"?>
<transcript>
  <text start="0.0" dur="1.0">Hello</text>
</transcript>`

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/xml")
		w.Write([]byte(captionXML))
	}))
	defer srv.Close()

	client := &Client{
		yt: &ytlib.Client{HTTPClient: srv.Client()},
	}

	video := &ytlib.Video{
		CaptionTracks: []ytlib.CaptionTrack{
			{
				BaseURL:      srv.URL + "/en",
				LanguageCode: "en",
				Name: struct {
					SimpleText string `json:"simpleText"`
				}{SimpleText: "English"},
			},
			{
				BaseURL:      srv.URL + "/es",
				LanguageCode: "es",
				Kind:         "asr",
				Name: struct {
					SimpleText string `json:"simpleText"`
				}{SimpleText: "Spanish"},
			},
		},
	}

	tracks, err := client.GetAllTranscripts(context.Background(), video)
	if err != nil {
		t.Fatalf("GetAllTranscripts() error = %v", err)
	}

	if len(tracks) != 2 {
		t.Fatalf("got %d tracks, want 2", len(tracks))
	}

	// Check auto-generated detection
	var found bool
	for _, tr := range tracks {
		if tr.LanguageCode == "es" {
			found = true
			if !tr.AutoGenerated {
				t.Error("Spanish track should be auto-generated")
			}
		}
	}
	if !found {
		t.Error("Spanish track not found")
	}
}

func TestCaptionTrackStruct(t *testing.T) {
	// Verify CaptionTrack fields
	track := store.CaptionTrack{
		Language:      "English",
		LanguageCode:  "en",
		AutoGenerated: false,
		Text:          "hello world",
	}

	if track.Language != "English" {
		t.Errorf("unexpected Language: %s", track.Language)
	}
}
