package youtube

import (
	"context"
	"encoding/xml"
	"fmt"
	"html"
	"io"
	"net/http"
	"strings"

	"greenclaw/internal/store"

	ytlib "github.com/kkdai/youtube/v2"
)

// TimedEntry represents a single timed text entry from YouTube's caption XML.
type TimedEntry struct {
	Start float64 `xml:"start,attr"`
	Dur   float64 `xml:"dur,attr"`
	Text  string  `xml:",chardata"`
}

// timedTextXML is the root element of YouTube's timed text format.
type timedTextXML struct {
	Entries []TimedEntry `xml:"text"`
}

// GetTranscript fetches a single caption track by language code.
func (c *Client) GetTranscript(ctx context.Context, video *ytlib.Video, langCode string) (*store.CaptionTrack, []TimedEntry, error) {
	for _, cap := range video.CaptionTracks {
		if cap.LanguageCode == langCode {
			entries, err := c.fetchCaptionTrack(ctx, cap.BaseURL)
			if err != nil {
				return nil, nil, err
			}
			text := entriesToPlainText(entries)
			track := &store.CaptionTrack{
				Language:      cap.Name.SimpleText,
				LanguageCode:  cap.LanguageCode,
				AutoGenerated: cap.Kind == "asr",
				Text:          text,
			}
			return track, entries, nil
		}
	}
	return nil, nil, fmt.Errorf("no caption track found for language: %s", langCode)
}

// GetAllTranscripts fetches all available caption tracks.
func (c *Client) GetAllTranscripts(ctx context.Context, video *ytlib.Video) ([]store.CaptionTrack, error) {
	var tracks []store.CaptionTrack
	for _, cap := range video.CaptionTracks {
		entries, err := c.fetchCaptionTrack(ctx, cap.BaseURL)
		if err != nil {
			continue // skip tracks that fail to fetch
		}
		tracks = append(tracks, store.CaptionTrack{
			Language:      cap.Name.SimpleText,
			LanguageCode:  cap.LanguageCode,
			AutoGenerated: cap.Kind == "asr",
			Text:          entriesToPlainText(entries),
		})
	}
	return tracks, nil
}

// GetTranscriptEntries fetches raw timed entries for a caption track by language code.
func (c *Client) GetTranscriptEntries(ctx context.Context, video *ytlib.Video, langCode string) ([]TimedEntry, error) {
	for _, cap := range video.CaptionTracks {
		if cap.LanguageCode == langCode {
			return c.fetchCaptionTrack(ctx, cap.BaseURL)
		}
	}
	return nil, fmt.Errorf("no caption track found for language: %s", langCode)
}

func (c *Client) fetchCaptionTrack(ctx context.Context, baseURL string) ([]TimedEntry, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, baseURL, nil)
	if err != nil {
		return nil, fmt.Errorf("creating caption request: %w", err)
	}

	httpClient := c.yt.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetching caption track: %w", err)
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("reading caption data: %w", err)
	}

	return parseTimedTextXML(data)
}

// parseTimedTextXML parses YouTube's timed text XML format.
func parseTimedTextXML(data []byte) ([]TimedEntry, error) {
	var tt timedTextXML
	if err := xml.Unmarshal(data, &tt); err != nil {
		return nil, fmt.Errorf("parsing timed text XML: %w", err)
	}

	// Unescape HTML entities in text
	for i := range tt.Entries {
		tt.Entries[i].Text = html.UnescapeString(tt.Entries[i].Text)
	}

	return tt.Entries, nil
}

// entriesToPlainText joins timed entries into a single text string.
func entriesToPlainText(entries []TimedEntry) string {
	var b strings.Builder
	for i, e := range entries {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(strings.TrimSpace(e.Text))
	}
	return b.String()
}
